package word.search.graphics;

import com.badlogic.gdx.graphics.g2d.TextureAtlas;

import word.search.managers.ResourceManager;

public class AtlasRegions {

    public static TextureAtlas.AtlasRegion welcome;
    public static TextureAtlas.AtlasRegion letter_holder;
    public static TextureAtlas.AtlasRegion game_button_word_letter, game_button_board_letter, game_button_magic_wand, game_button_rotate;
    public static TextureAtlas.AtlasRegion sparkle;
    public static TextureAtlas.AtlasRegion sparkle_small;
    public static TextureAtlas.AtlasRegion placeholder_coin;
    public static TextureAtlas.AtlasRegion coin_view_bg;
    public static TextureAtlas.AtlasRegion coin_view_coin;
    public static TextureAtlas.AtlasRegion coin_view_plus_up;
    public static TextureAtlas.AtlasRegion coin_small;
    public static TextureAtlas.AtlasRegion close_btn_up;
    public static TextureAtlas.AtlasRegion progressbar;
    public static TextureAtlas.AtlasRegion progressbar_track;
    public static TextureAtlas.AtlasRegion cup;
    public static TextureAtlas.AtlasRegion cup_ribbon;
    public static TextureAtlas.AtlasRegion star3d;
    public static TextureAtlas.AtlasRegion level_end_box;
    public static TextureAtlas.AtlasRegion level_end_box_lid;
    public static TextureAtlas.AtlasRegion coins_level_end;
    public static TextureAtlas.AtlasRegion level_end_rays, daily_rays;
    public static TextureAtlas.AtlasRegion btn_back, btn_settings;
    public static TextureAtlas.AtlasRegion fx_icon, music_icon, share_icon;
    public static TextureAtlas.AtlasRegion btn_green;
    public static TextureAtlas.AtlasRegion email_icon;
    public static TextureAtlas.AtlasRegion arrow_left, arrow_right;
    public static TextureAtlas.AtlasRegion loading;
    public static TextureAtlas.AtlasRegion wordnik_badge_a1;
    public static TextureAtlas.AtlasRegion dictionary_icon;
    public static TextureAtlas.AtlasRegion play;
    public static TextureAtlas.AtlasRegion pcircle;
    public static TextureAtlas.AtlasRegion btn_bonus;
    public static TextureAtlas.AtlasRegion coin_view;
    public static TextureAtlas.AtlasRegion box1_a, box1_b, box2_a, box2_b, box3_a, box3_b;
    public static TextureAtlas.AtlasRegion reward_coin, reward_magic_wand, reward_single_letter_board, reward_single_letter_word;
    public static TextureAtlas.AtlasRegion ic_video_small;
    public static TextureAtlas.AtlasRegion cost_25, cost_50, cost_100;
    public static TextureAtlas.AtlasRegion tent, btn_back_iap;
    public static TextureAtlas.AtlasRegion iap_bundle_big, iap_bundle_super, iap_bundle_mega;
    public static TextureAtlas.AtlasRegion ic_magic_wand, ic_magnifier, ic_bulb, noads;
    public static TextureAtlas.AtlasRegion iap_coin, iap_coins, coin_bg;
    public static TextureAtlas.AtlasRegion watch_and_earn_coins;
    public static TextureAtlas.AtlasRegion checkbox_checked, checkbox_unchecked;
    public static TextureAtlas.AtlasRegion pb_start_bg, pb_mid_bg, pb_end_bg, pb_start, pb_mid, pb_end, pb_glow;
    public static TextureAtlas.AtlasRegion ad_btn_bg, coins_ad_button, ad_rays;
    public static TextureAtlas.AtlasRegion level_board;
    public static TextureAtlas.AtlasRegion arrow, hand;
    public static TextureAtlas.AtlasRegion place_holder_ring;
    public static TextureAtlas.AtlasRegion bonus_glow;
    public static TextureAtlas.AtlasRegion padlock;
    public static TextureAtlas.AtlasRegion magic_wand, magic;
    public static TextureAtlas.AtlasRegion btn_settings_row, btn_lang, lang_glow;
    public static TextureAtlas.AtlasRegion disabled;
    public static TextureAtlas.AtlasRegion bird_1, bird_2, bird_3, bird_4, bird_5, bird_6, bird_7, bird_8, bird_9;
    public static TextureAtlas.AtlasRegion hint_bg;


    public static void init(ResourceManager resourceManager){
        TextureAtlas atlas1             = resourceManager.get(ResourceManager.ATLAS_1, TextureAtlas.class);

        welcome                         = atlas1.findRegion("welcome");
        letter_holder                   = atlas1.findRegion("letter_holder");
        game_button_word_letter         = atlas1.findRegion("game_button_word_letter");
        game_button_board_letter        = atlas1.findRegion("game_button_board_letter");
        game_button_magic_wand          = atlas1.findRegion("game_button_magic_wand");
        game_button_rotate              = atlas1.findRegion("game_button_rotate");
        sparkle                         = atlas1.findRegion("sparkle");
        sparkle_small                   = atlas1.findRegion("sparkle_small");
        placeholder_coin                = atlas1.findRegion("placeholder_coin");
        coin_view_bg                    = atlas1.findRegion("coin_view_bg");
        coin_view_coin                  = atlas1.findRegion("coin_view_coin");
        coin_view_plus_up               = atlas1.findRegion("coin_view_plus_up");
        coin_small                      = atlas1.findRegion("coin_small");
        close_btn_up                    = atlas1.findRegion("close_btn_up");
        progressbar                     = atlas1.findRegion("progressbar");
        progressbar_track               = atlas1.findRegion("progressbar_track");
        cup                             = atlas1.findRegion("cup");
        cup_ribbon                      = atlas1.findRegion("cup_ribbon");
        star3d                          = atlas1.findRegion("star3d");
        level_end_box                   = atlas1.findRegion("level_end_box");
        level_end_box_lid               = atlas1.findRegion("level_end_box_lid");
        coins_level_end                 = atlas1.findRegion("coins_level_end");
        level_end_rays                  = atlas1.findRegion("level_end_rays");
        btn_back                        = atlas1.findRegion("btn_back");
        btn_settings                    = atlas1.findRegion("btn_settings");
        fx_icon                         = atlas1.findRegion("fx_icon");
        music_icon                      = atlas1.findRegion("music_icon");
        share_icon                      = atlas1.findRegion("share_icon");
        btn_green                       = atlas1.findRegion("btn_green");
        email_icon                      = atlas1.findRegion("email_icon");
        arrow_left                      = atlas1.findRegion("arrow_left");
        arrow_right                     = atlas1.findRegion("arrow_right");
        loading                         = atlas1.findRegion("loading");
        wordnik_badge_a1                = atlas1.findRegion("wordnik_badge_a3");
        dictionary_icon                 = atlas1.findRegion("dictionary_icon");
        play                            = atlas1.findRegion("play");
        pcircle                         = atlas1.findRegion("pcircle");
        btn_bonus                       = atlas1.findRegion("btn_bonus");
        coin_view                       = atlas1.findRegion("coin_view");
        box1_a                          = atlas1.findRegion("box1_a");
        box1_b                          = atlas1.findRegion("box1_b");
        box2_a                          = atlas1.findRegion("box2_a");
        box2_b                          = atlas1.findRegion("box2_b");
        box3_a                          = atlas1.findRegion("box3_a");
        box3_b                          = atlas1.findRegion("box3_b");
        reward_coin                     = atlas1.findRegion("reward_coin");
        reward_magic_wand               = atlas1.findRegion("reward_magic_wand");
        reward_single_letter_board      = atlas1.findRegion("reward_single_letter_board");
        reward_single_letter_word       = atlas1.findRegion("reward_single_letter_word");
        daily_rays                      = atlas1.findRegion("daily_rays");
        ic_video_small                  = atlas1.findRegion("ic_video_small");
        cost_25                         = atlas1.findRegion("cost_25");
        cost_50                         = atlas1.findRegion("cost_50");
        cost_100                        = atlas1.findRegion("cost_100");
        btn_back_iap                    = atlas1.findRegion("btn_back_iap");
        tent                            = atlas1.findRegion("tent");
        iap_bundle_big                  = atlas1.findRegion("iap_bundle_big");
        iap_bundle_super                = atlas1.findRegion("iap_bundle_super");
        iap_bundle_mega                 = atlas1.findRegion("iap_bundle_mega");
        ic_magic_wand                   = atlas1.findRegion("ic_magic_wand");
        ic_magnifier                    = atlas1.findRegion("ic_magnifier");
        ic_bulb                         = atlas1.findRegion("ic_bulb");
        noads                           = atlas1.findRegion("noads");
        iap_coin                        = atlas1.findRegion("iap_coin");
        iap_coins                       = atlas1.findRegion("iap_coins");
        coin_bg                         = atlas1.findRegion("coin_bg");
        watch_and_earn_coins            = atlas1.findRegion("watch_and_earn_coins");
        checkbox_checked                = atlas1.findRegion("checkbox_checked");
        checkbox_unchecked              = atlas1.findRegion("checkbox_unchecked");
        pb_start_bg                     = atlas1.findRegion("pb_start_bg");
        pb_mid_bg                       = atlas1.findRegion("pb_mid_bg");
        pb_end_bg                       = atlas1.findRegion("pb_end_bg");
        pb_start                        = atlas1.findRegion("pb_start");
        pb_mid                          = atlas1.findRegion("pb_mid");
        pb_end                          = atlas1.findRegion("pb_end");
        pb_glow                         = atlas1.findRegion("pb_glow");
        ad_btn_bg                       = atlas1.findRegion("ad_btn_bg");
        coins_ad_button                 = atlas1.findRegion("coins_ad_button");
        ad_rays                         = atlas1.findRegion("ad_rays");
        level_board                     = atlas1.findRegion("level_board");
        arrow                           = atlas1.findRegion("arrow");
        hand                            = atlas1.findRegion("hand");
        place_holder_ring               = atlas1.findRegion("place_holder_ring");
        bonus_glow                      = atlas1.findRegion("bonus_glow");
        padlock                         = atlas1.findRegion("padlock");
        magic_wand                      = atlas1.findRegion("magic_wand");
        magic                           = atlas1.findRegion("magic");
        btn_settings_row                = atlas1.findRegion("btn_settings_row");
        btn_lang                        = atlas1.findRegion("btn_lang");
        lang_glow                       = atlas1.findRegion("lang_glow");
        disabled                        = atlas1.findRegion("disabled");
        bird_1                          = atlas1.findRegion("bird_1");
        bird_2                          = atlas1.findRegion("bird_2");
        bird_3                          = atlas1.findRegion("bird_3");
        bird_4                          = atlas1.findRegion("bird_4");
        bird_5                          = atlas1.findRegion("bird_5");
        bird_6                          = atlas1.findRegion("bird_6");
        bird_7                          = atlas1.findRegion("bird_7");
        bird_8                          = atlas1.findRegion("bird_8");
        bird_9                          = atlas1.findRegion("bird_9");
        hint_bg                         = atlas1.findRegion("hint_bg");
    }

}
